services:
  - type: web
    name: gaymeet-api
    runtime: node
    rootDir: backend-express
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
